import type { Metadata } from "next";
import "./globals.css";
import { groteskFont } from "./ui/font";

export const metadata: Metadata = {
  title: "Positivus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${groteskFont.className}`}
      >
        {children}
      </body>
    </html>
  );
}
