import type { Metadata } from "next";
import "./globals.css";
import { groteskFont } from "./ui/font";
import Navigation from "@/features/shell/navigation";
import Footer from "@/features/shell/footer";

export const metadata: Metadata = {
  title: "Positivus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${groteskFont.className} lg:px-25 py-15 `}
      >
        <Navigation />
        <main className="mt-16 mb-35">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
